branches:
  except:
    - draft
    - tmp
    - /.*\.(draft|tmp)$/
    - /^(draft|tmp)\..*/

language: minimal

cache:
  directories:
    - $HOME/.cache/deno
    - $HOME/.pnpm-store
    - $HOME/.node-gyp
    - $HOME/.node_libraries

dist: bionic

addons:
  apt:
    packages:
      - zsh

env:
  - DENO_VERSION=v1.0.0
    SANE_FMT_VERSION=0.2.22

install:
  - curl -fsSL https://deno.land/x/install/install.sh | sh -s $DENO_VERSION
  - sudo ln -s "$HOME/.deno/bin/deno" /bin/deno
  - sudo sh ./ci/install-sane-fmt.sh

script:
  - export SHELL=/bin/zsh
  - deno run --allow-all --unstable ./Drakefile.ts all
