branches:
  except:
    - draft
    - tmp
    - /.*\.(draft|tmp)$/
    - /^(draft|tmp)\..*/

language: minimal

cache:
  directories:
    - $HOME/.cache/deno
    - $HOME/.pnpm-store
    - $HOME/.node-gyp
    - $HOME/.node_libraries

dist: bionic

addons:
  apt:
    packages:
      - zsh
      - curl

env:
  - DENO_VERSION=v0.41.0
    EXECUTABLE_FACTORY_TAG=0.1.0

install:
  - curl -fsSL https://deno.land/x/install/install.sh | sh -s $DENO_VERSION
  - sudo ln -s "$HOME/.deno/bin/deno" /bin/deno
  - sudo --preserve-env=EXECUTABLE_FACTORY_TAG ./ci/install-prettier.bash

script:
  - export SHELL=/bin/zsh
  - deno run --allow-all ./Drakefile.ts all
