branches:
  except:
    - draft
    - tmp
    - /.*\.(draft|tmp)$/
    - /^(draft|tmp)\..*/

language: minimal

cache:
  directories:
    - $HOME/.deno
    - $HOME/.pnpm-store
    - $HOME/.node-gyp
    - $HOME/.node_libraries

dist: bionic

addons:
  apt:
    packages:
      - zsh

env:
  - DENO_VERSION=v0.40.0

before_install:
  - echo HOME $HOME
  - echo TRAVIS_HOME $TRAVIS_HOME
  - ls -A $HOME/.deno
  - ls -A $TRAVIS_HOME/.deno
  - sh -c 'exit 1'

install:
  - curl -fsSL https://deno.land/x/install/install.sh | sh -s $DENO_VERSION
  - sudo ln -s "$HOME/.deno/bin/deno" /bin/deno

script:
  - export SHELL=/bin/zsh
  - deno run --allow-all ./Drakefile.ts all
