branches:
  except:
    - draft
    - tmp
    - /.*\.(draft|tmp)$/
    - /^(draft|tmp)\..*/

language: minimal

cache:
  directories:
    - $HOME/.deno
    - $HOME/.pnpm-store
    - $HOME/.node-gyp
    - $HOME/.node_libraries

dist: bionic

addons:
  apt:
    packages:
      - zsh
      - tree

env:
  - DENO_VERSION=v0.40.0

install:
  - curl -fsSL https://deno.land/x/install/install.sh | sh -s $DENO_VERSION
  - sudo ln -s "$HOME/.deno/bin/deno" /bin/deno
  - zsh -c 'deno cache **/*.ts; deno cache **/*.js; true'
  - echo HOME $HOME
  - echo TRAVIS_HOME $TRAVIS_HOME
  - tree $HOME/.deno
  - tree $TRAVIS_HOME/.deno
  - false

script:
  - export SHELL=/bin/zsh
  - deno run --allow-all ./Drakefile.ts all
