name: CI

on:
  - push
  - pull_request

env:
  SHELL: /bin/zsh

jobs:
  all:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        vars:
          - deno: v0.41.0

    steps:
      - uses: actions/checkout@v2
      - name: Install some necessary programs
        run: |
          sudo apt install -y zsh
      - name: Test JavaScript
        env:
          # JSON_STR: ${{ JSON.stringify([0, 1, 2, 3]) }}
          # FUNCTION_STR: ${{ String(Function) }}
          GLOBAL_KEYS: ${{ Object.keys(globalThis) }}
        run: |
          # zsh -c 'echo JSON $JSON_STR'
          # zsh -c 'echo FUNCTION $FUNCTION_STR'
          zsh -c 'echo GLOBAL $GLOBAL_KEYS'
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/deno
          key: deno-${{ runner.os }}-${{ hashFiles('deno-lock.json') }}
          restore-keys: |
            deno-${{ runner.os }}-${{ hashFiles('deno-lock.json') }}
            deno-${{ runner.os }}-
            deno-
      - name: Install Deno
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh -s ${{ matrix.vars.deno }}
          sudo ln -s "$HOME/.deno/bin/deno" /bin/deno
      - name: Run all targets in Drakefile
        run: |
          deno run --allow-all Drakefile.ts all
