name: CI

on:
  - push
  - pull_request

env:
  SHELL: /bin/zsh

jobs:
  all:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
      - name: Install some necessary programs
        run: |
          sudo apt install -y zsh
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/deno
          key: deno-${{ runner.os }}-${{ hashFiles('deno-lock.json') }}
          restore-keys: |
            deno-${{ runner.os }}-${{ hashFiles('deno-lock.json') }}
            deno-${{ runner.os }}-
            deno-
      - name: Install Deno
        uses: denolib/setup-deno@v1.3.0
        with:
          deno-version: 0.41.0
      - name: Run all targets in Drakefile
        run: |
          deno run --allow-all Drakefile.ts all
      - name: Upload deno cache as artifacts
        uses: actions/upload-artifact@v1
        with:
          name: deno-cache
          path: $HOME/.cache/deno
