name: CI

on:
  - push
  - pull_request

env:
  SHELL: /bin/zsh

jobs:
  all:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        vars:
          - deno: v0.41.0

    steps:
      - uses: actions/checkout@v2
      - name: Inspect variables
        run: |
          echo github.action = ${{ github.action }}
          echo github.event_name = ${{ github.event_name }}
          echo github.sha = ${{ github.sha }}
          echo github.ref = ${{ github.ref }}
      - name: Install some necessary programs
        run: |
          sudo apt install -y zsh
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/deno
          key: deno-${{ runner.os }}-${{ hashFiles('deno-lock.json') }}
          restore-keys: |
            deno-${{ runner.os }}-${{ hashFiles('deno-lock.json') }}
            deno-${{ runner.os }}-
            deno-
      - name: Install Deno
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh -s ${{ matrix.vars.deno }}
          sudo ln -s "$HOME/.deno/bin/deno" /bin/deno
      - name: Run all targets in Drakefile
        run: |
          deno run --allow-all Drakefile.ts all
