name: CI

on:
  - push
  - pull_request

env:
  SHELL: /bin/zsh

jobs:
  all:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
      - name: Install some necessary programs
        run: |
          sudo apt install -y zsh
      - name: Install sane-fmt
        uses: KSXGitHub/github-actions-sane-fmt@0.2.23
        with:
          run: 'false'
          export-path: 'true'
      - name: Cache
        timeout-minutes: 1
        continue-on-error: true
        uses: actions/cache@v2
        with:
          path: ~/.cache/deno
          key: deno-${{ runner.os }}-${{ hashFiles('**/deps.ts') }}
          restore-keys: |
            deno-${{ runner.os }}-${{ hashFiles('**/deps.ts') }}
            deno-${{ runner.os }}-
            deno-
      - name: Install Deno
        uses: denolib/setup-deno@v1.3.0
        with:
          deno-version: 1.0.0
      - name: Run all targets in Drakefile
        run: |
          deno run --allow-all --unstable Drakefile.ts all
      - name: Prepare for uploading deno cache as artifacts
        run: |
          cp -r ~/.cache/deno deno-cache.tmp
      - name: Upload deno cache as artifacts
        uses: actions/upload-artifact@v1
        with:
          name: deno-cache
          path: deno-cache.tmp

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: KSXGitHub/github-actions-sane-fmt@0.2.22
