name: CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/deno-action@0.20.0
      - name: Run all targets in Drakefile
        run: deno run --allow-all Drakefile.ts all
